// Writes `src/lib/dict/entities.js` - the HTML standard's table of named
// character references, which is what lets a dictionary entry's `&lsqb;` read
// as `[` (see `decodeEntities` in `src/lib/dict/text.js`).
//
// A development tool, not part of the build and not part of the gate: it
// needs the network. The standard calls its table final - no name will be
// added or changed - so this was run once and its output committed; the tool
// is kept so that the table can be regenerated and compared rather than
// taken on trust.
//
// Usage:
//   node tools/entities.mjs            # downloads the standard's entities.json
//   node tools/entities.mjs <file>     # reads a copy already downloaded
//
// Behind a proxy (the sandbox this repository is developed in is one), Node
// needs to be told: `NODE_USE_ENV_PROXY=1 node tools/entities.mjs`.

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT = join(ROOT, "src", "lib", "dict", "entities.js");

/** The standard's own machine-readable copy of the table. */
const SOURCE = "https://html.spec.whatwg.org/entities.json";

/** The page a reader checks the table against, one row per name. */
const REFERENCE = "https://html.spec.whatwg.org/multipage/named-characters.html";

/**
 * @typedef {object} Reference
 * @property {number[]} codepoints one or two
 * @property {string} characters the same, as a string
 */

/**
 * @returns {Promise<string>}
 */
async function fetchJson() {
  const response = await fetch(SOURCE);
  if (!response.ok) throw new Error(`${response.status} ${response.statusText} for ${SOURCE}`);
  return await response.text();
}

const from = process.argv[2];
const json = from === undefined ? await fetchJson() : await readFile(from, "utf8");
/** @type {Record<string, Reference>} */
const table = JSON.parse(json);

/**
 * A code point as a JavaScript string literal writes it: printable ASCII as
 * itself, everything else by number - the file has to read in a diff, and
 * the table is checked against the standard's page, which lists code points.
 *
 * @param {number} code
 * @returns {string}
 */
function escaped(code) {
  if (code === 0x22 || code === 0x5c) return `\\${String.fromCodePoint(code)}`;
  if (code >= 0x20 && code <= 0x7e) return String.fromCodePoint(code);
  return code > 0xffff ? `\\u{${code.toString(16)}}` : `\\u${code.toString(16).padStart(4, "0")}`;
}

/** @type {string[]} */
const lines = [];
let legacy = 0;
for (const [written, reference] of Object.entries(table).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))) {
  if (!written.startsWith("&")) throw new Error(`not a reference: ${written}`);
  // The standard keeps 106 legacy spellings a browser also decodes without
  // the semicolon (`&amp`, `&copy`); the decoder here asks for the semicolon,
  // and every one of them has a spelling with it in the table as well.
  if (!written.endsWith(";")) {
    legacy += 1;
    continue;
  }
  const name = written.slice(1, -1);
  if (!/^[A-Za-z][A-Za-z0-9]*$/.test(name)) throw new Error(`a name that is not a name: ${written}`);
  if (reference.codepoints.length === 0 || reference.codepoints.length > 2) {
    throw new Error(`${written} stands for ${reference.codepoints.length} code points`);
  }
  if (String.fromCodePoint(...reference.codepoints) !== reference.characters) {
    throw new Error(`${written}: code points and characters disagree`);
  }
  lines.push(`  ${name}: "${reference.codepoints.map(escaped).join("")}",`);
}

if (lines.length === 0) throw new Error("the table matched nothing - has its layout changed?");

const header = `/**
 * The HTML standard's named character references: every \`&name;\` a browser
 * decodes, as the standard lists them (${REFERENCE}).
 *
 * GENERATED by \`tools/entities.mjs\` from the standard's \`entities.json\`
 * (${SOURCE}) - ${lines.length} names; the ${legacy} legacy
 * spellings without a semicolon are left out, see \`decodeEntities\` in
 * \`text.js\`. Not edited by hand: regenerated and compared. The standard
 * calls the table final.
 *
 * Written by code point wherever the character is not printable ASCII - the
 * way this project writes every invisible character, and the way the
 * standard's page lists them, so a line can be checked against it.
 *
 * Marked pure so that a bundle which never decodes an entry - the popup
 * lists the dictionaries and asks nothing of them - is built without it.
 *
 * @type {Readonly<Record<string, string>>}
 */
export const ENTITIES = /* @__PURE__ */ Object.freeze({
`;

await writeFile(OUT, `${header}${lines.join("\n")}\n});\n`);
console.log(`wrote ${OUT}: ${lines.length} names (${legacy} legacy spellings left out)`);
