// Writes `src/lib/dict/catalog.json` - the list of dictionaries the settings
// page offers to download.
//
// This is a development tool, not part of the build and not part of the gate:
// it needs the network. It is run by hand when WikDict adds pairs, and its
// output is committed. Unlike `models-registry.mjs` it downloads nothing but
// the directory listing, and it computes no checksums - WikDict rebuilds its
// archives in place, so pinned sums would break with every rebuild. The
// extension's guard for these downloads is described in
// `src/lib/dict/download.js`.
//
// Usage:
//   node tools/wikdict-catalog.mjs
//
// Behind a proxy (the sandbox this repository is developed in is one), Node
// needs to be told: `NODE_USE_ENV_PROXY=1 node tools/wikdict-catalog.mjs` -
// and the proxy has to allow the host at all.

import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT = join(ROOT, "src", "lib", "dict", "catalog.json");

/** The one directory WikDict publishes its StarDict builds in. */
const LISTING = "https://download.wikdict.com/dictionaries/stardict/";

const response = await fetch(LISTING);
if (!response.ok) {
  throw new Error(`${response.status} ${response.statusText} for ${LISTING}`);
}
const html = await response.text();

// An nginx autoindex: one <a href="wikdict-xx-yy.zip"> per file. The pattern
// is the contract; anything the regex does not match is not a dictionary
// archive and is left where it is.
/** @type {{ from: string, to: string, url: string }[]} */
const entries = [];
const seen = new Set();
for (const match of html.matchAll(/href="(wikdict-([a-z]{2,3})-([a-z]{2,3})\.zip)"/g)) {
  const [, name, from, to] = match;
  if (name === undefined || from === undefined || to === undefined) continue;
  if (seen.has(name)) continue;
  seen.add(name);
  entries.push({ from, to, url: `${LISTING}${name}` });
}

if (entries.length === 0) {
  throw new Error("the listing matched nothing - has its layout changed?");
}

entries.sort((a, b) => a.from.localeCompare(b.from) || a.to.localeCompare(b.to));

const catalog = {
  comment:
    "Generated by tools/wikdict-catalog.mjs - the list of dictionaries the settings page " +
    "offers to download, one entry per WikDict archive. No checksums on purpose: WikDict " +
    "rebuilds its files in place, so a sum pinned here would break with every rebuild; " +
    "see src/lib/dict/download.js for what stands guard instead.",
  source: LISTING,
  checkedAt: new Date().toISOString().slice(0, 10),
  dictionaries: entries,
};

await writeFile(OUT, JSON.stringify(catalog, null, 2) + "\n");
console.log(`wrote ${OUT}: ${entries.length} dictionaries`);
